---
- name: nginx install and start services
  hosts: localhost
  connection: local 
  #become: true

  tasks:
  - name: install nginx
    yum:
     name: nginx
     state: latest
  - name: start nginx
    service:
      name: nginx
      start: started 
